//! PR-KV8 RED — gear (spline-annotated) profile extrusion + booleans.
//!
//! The assay corpus's single biggest blocker (73 of 193 cases) is the gear
//! profile: `make_faces_from_profiles` rejects any profile carrying
//! `spline_segments`. But a gear `ClosedProfile`'s **`vertex_ids` IS the
//! complete authored boundary polygon** — the involute flank sample points
//! plus the tip/root arc endpoints, generated by
//! `waffle_types::generate_gear_profile` (the same canonical polygon the
//! sketch solver and viewport use, and the polygon the legacy kernel
//! extruded). The `SplineSegment` entries are annotations over that
//! polygon (fitted control points for a NURBS-capable kernel); they do not
//! change the profile's authored geometry.
//!
//! So the principled kernel-v2 handling is to consume the authored polygon
//! exactly: the solid IS the extrusion of that (non-convex, exactly-simple)
//! polygon, with the exact ear-clip tessellation and exact shoelace area —
//! no new sampling, no approximation introduced by the kernel. This matches
//! the roadmap's designation of gear profiles as "non-convex CDT" work.
//!
//! Profiles with `arc_segments` stay WALLED: their vertex_ids carry arc
//! sample points where an EXACT cylindrical wall is representable
//! (post-KV5b), so polygonizing them would discard achievable exactness —
//! that support is its own milestone.

use std::collections::HashMap;

use kernel_v2::KernelV2Adapter;
use waffle_types::gear::{generate_gear_profile, GearParams};
use waffle_types::kernel::Kernel;

/// A small corpus-like gear: 11 teeth, module 3.47 (≈ R0012's first op).
fn gear_params() -> GearParams {
    GearParams {
        tooth_count: 11,
        module: 3.4745960218024408,
        pressure_angle_deg: 20.0,
        backlash: 0.0,
        center_x: 0.0,
        center_y: 0.0,
        rotation_offset: 0.0,
    }
}

/// Exact shoelace area of the profile's authored vertex_ids polygon.
fn polygon_area(vertex_ids: &[u32], positions: &HashMap<u32, (f64, f64)>) -> f64 {
    let pts: Vec<(f64, f64)> = vertex_ids.iter().map(|id| positions[id]).collect();
    let n = pts.len();
    let mut s2 = 0.0;
    for i in 0..n {
        let (x0, y0) = pts[i];
        let (x1, y1) = pts[(i + 1) % n];
        s2 += x0 * y1 - x1 * y0;
    }
    (s2 / 2.0).abs()
}

fn mesh_signed_volume(mesh: &waffle_types::kernel::RenderMesh) -> f64 {
    let p = |i: u32| {
        let k = (i as usize) * 3;
        [
            mesh.vertices[k] as f64,
            mesh.vertices[k + 1] as f64,
            mesh.vertices[k + 2] as f64,
        ]
    };
    let mut six_v = 0.0;
    for t in mesh.indices.chunks_exact(3) {
        let (a, b, c) = (p(t[0]), p(t[1]), p(t[2]));
        six_v += a[0] * (b[1] * c[2] - b[2] * c[1])
            + a[1] * (b[2] * c[0] - b[0] * c[2])
            + a[2] * (b[0] * c[1] - b[1] * c[0]);
    }
    six_v / 6.0
}

#[test]
fn gear_profile_extrudes_with_exact_polygon_volume() {
    let g = generate_gear_profile(&gear_params());
    let profile = g.profiles[0].clone();
    assert!(
        !profile.spline_segments.is_empty(),
        "fixture must carry spline annotations"
    );
    let area = polygon_area(&profile.vertex_ids, &g.positions);
    assert!(area > 0.0);

    let mut k = KernelV2Adapter::new();
    let faces = k
        .make_faces_from_profiles(
            &[profile],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &g.positions,
        )
        .unwrap_or_else(|e| panic!("gear profile staging: {e:?}"));
    let depth = 5.0;
    let solid = k
        .extrude_face(faces[0], [0.0, 0.0, 1.0], depth)
        .unwrap_or_else(|e| panic!("gear extrude: {e:?}"));
    let mesh = k.tessellate(&solid, 0.001).expect("tessellate");
    let vol = mesh_signed_volume(&mesh);
    let expect = area * depth;
    // The polygon is the authored profile; its extrusion volume is exact
    // (ear-clip caps are an exact partition; walls are exact planes). The
    // band absorbs ONLY the RenderMesh's f32 vertex quantization (the
    // kernel geometry is f64-exact; the render channel rounds coordinates
    // to f32, ~1e-7 relative per vertex).
    assert!(
        (vol - expect).abs() <= 1e-6 * expect.max(1.0),
        "gear prism volume {vol} vs exact {expect}"
    );
}

/// Gear boss unioned onto a rectangular slab — the corpus's 2-op shape.
/// Volume by inclusion–exclusion: the gear prism's overlap with the slab is
/// gear_area × overlap height (footprint fully inside the slab).
#[test]
fn gear_boss_union_on_slab() {
    let g = generate_gear_profile(&gear_params());
    let profile = g.profiles[0].clone();
    let area = polygon_area(&profile.vertex_ids, &g.positions);
    // Addendum radius bounds the footprint.
    let r_out = g.addendum_radius;

    let mut k = KernelV2Adapter::new();
    // Slab: big rect covering the gear footprint, z ∈ [0, 4].
    let half = r_out * 2.0;
    let mut rect_positions = HashMap::new();
    rect_positions.insert(1, (-half, -half));
    rect_positions.insert(2, (half, -half));
    rect_positions.insert(3, (half, half));
    rect_positions.insert(4, (-half, half));
    let rect_profile = waffle_types::ClosedProfile {
        entity_ids: vec![1, 2, 3, 4],
        is_outer: true,
        vertex_ids: vec![1, 2, 3, 4],
        circle: None,
        spline_segments: vec![],
        arc_segments: vec![],
    };
    let rf = k
        .make_faces_from_profiles(
            &[rect_profile],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &rect_positions,
        )
        .expect("rect profile");
    let slab = k.extrude_face(rf[0], [0.0, 0.0, 1.0], 4.0).expect("slab");

    // Gear boss: z ∈ [2, 9] (sketch plane mid-slab → boss pokes out the top;
    // avoids any coplanar contact with the slab caps).
    let gf = k
        .make_faces_from_profiles(
            &[profile],
            [0.0, 0.0, 2.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &g.positions,
        )
        .expect("gear profile");
    let boss = k
        .extrude_face(gf[0], [0.0, 0.0, 1.0], 7.0)
        .expect("gear boss");

    let out = k
        .boolean_union(&slab, &boss)
        .unwrap_or_else(|e| panic!("gear boss union: {e:?}"));
    let mesh = k.tessellate(&out, 0.001).expect("tessellate union");
    let vol = mesh_signed_volume(&mesh);
    let slab_v = (2.0 * half) * (2.0 * half) * 4.0;
    let overlap = area * 2.0; // gear prism inside slab: z ∈ [2, 4]
    let expect = slab_v + area * 7.0 - overlap;
    // 1e-6 relative: f32 render-mesh quantization only (see prism test).
    assert!(
        (vol - expect).abs() <= 1e-6 * expect,
        "union volume {vol} vs exact {expect}"
    );
}

/// Gear pocket cut into a slab (the cut direction of the same class).
#[test]
fn gear_pocket_cut_into_slab() {
    let g = generate_gear_profile(&gear_params());
    let profile = g.profiles[0].clone();
    let area = polygon_area(&profile.vertex_ids, &g.positions);
    let r_out = g.addendum_radius;

    let mut k = KernelV2Adapter::new();
    let half = r_out * 2.0;
    let mut rect_positions = HashMap::new();
    rect_positions.insert(1, (-half, -half));
    rect_positions.insert(2, (half, -half));
    rect_positions.insert(3, (half, half));
    rect_positions.insert(4, (-half, half));
    let rect_profile = waffle_types::ClosedProfile {
        entity_ids: vec![1, 2, 3, 4],
        is_outer: true,
        vertex_ids: vec![1, 2, 3, 4],
        circle: None,
        spline_segments: vec![],
        arc_segments: vec![],
    };
    let rf = k
        .make_faces_from_profiles(
            &[rect_profile],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &rect_positions,
        )
        .expect("rect profile");
    let slab = k.extrude_face(rf[0], [0.0, 0.0, 1.0], 4.0).expect("slab");

    // Gear tool: enters through the top face (z ∈ [3, 6]) → pocket depth 1.
    let gf = k
        .make_faces_from_profiles(
            &[profile],
            [0.0, 0.0, 3.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &g.positions,
        )
        .expect("gear profile");
    let tool = k
        .extrude_face(gf[0], [0.0, 0.0, 1.0], 3.0)
        .expect("gear tool");
    let out = k
        .boolean_subtract(&slab, &tool)
        .unwrap_or_else(|e| panic!("gear pocket cut: {e:?}"));
    let mesh = k.tessellate(&out, 0.001).expect("tessellate cut");
    let vol = mesh_signed_volume(&mesh);
    let expect = (2.0 * half) * (2.0 * half) * 4.0 - area * 1.0;
    // 1e-6 relative: f32 render-mesh quantization only (see prism test).
    assert!(
        (vol - expect).abs() <= 1e-6 * expect,
        "pocket volume {vol} vs exact {expect}"
    );
}

fn arc_square_profile(vertex_ids: Vec<u32>) -> waffle_types::ClosedProfile {
    waffle_types::ClosedProfile {
        entity_ids: vec![1, 2, 3, 4],
        is_outer: true,
        vertex_ids,
        circle: None,
        spline_segments: vec![],
        arc_segments: vec![waffle_types::ArcSegment {
            start_vertex_index: 0,
            end_vertex_index: 1,
            center_u: 0.5,
            center_v: -0.5,
            radius: 0.7,
        }],
    }
}

fn unit_square_positions() -> HashMap<u32, (f64, f64)> {
    let mut positions = HashMap::new();
    positions.insert(1, (0.0, 0.0));
    positions.insert(2, (1.0, 0.0));
    positions.insert(3, (1.0, 1.0));
    positions.insert(4, (0.0, 1.0));
    positions
}

/// KV12 Tier 1: an arc-segment profile WITH a sampled `vertex_ids` polygon is
/// accepted — extruded via that authored chord polygon (the app pre-samples
/// each arc; `arc_segments` is annotation for a future exact cylinder wall).
#[test]
fn arc_segment_profile_with_vertex_ids_extrudes() {
    let profile = arc_square_profile(vec![1, 2, 3, 4]);
    let positions = unit_square_positions();
    let mut k = KernelV2Adapter::new();
    let ids = k
        .make_faces_from_profiles(
            &[profile],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &positions,
        )
        .expect("arc-segment profile with vertex_ids extrudes via the polygon (KV12 Tier 1)");
    assert_eq!(ids.len(), 1, "one staged profile");
}

/// Without a `vertex_ids` polygon there is nothing to extrude — the arc-segment
/// profile stays a loud typed wall (Tier 2 exact arc walls are a future milestone).
#[test]
fn arc_segment_profile_without_vertex_ids_stays_walled() {
    let profile = arc_square_profile(vec![]);
    let positions = unit_square_positions();
    let mut k = KernelV2Adapter::new();
    let err = k
        .make_faces_from_profiles(
            &[profile],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &positions,
        )
        .expect_err("arc-segment profile without vertex_ids stays walled");
    assert!(
        format!("{err}").contains("not supported"),
        "typed NotSupported, got {err}"
    );
}

/// KV14: a holed region drawn as ONE sketch — an outer `ClosedProfile` plus an
/// inner (`is_outer=false`) hole — extrudes as an annulus (the adapter now
/// assembles holes). Volume == (outer − hole) area × depth, and the output is
/// aligned 1:1 with the input profiles (profile_index contract).
#[test]
fn holed_sketch_extrudes_as_annulus() {
    let mut positions = HashMap::new();
    // Outer square [-5,5]² (ids 1-4, CCW).
    positions.insert(1, (-5.0, -5.0));
    positions.insert(2, (5.0, -5.0));
    positions.insert(3, (5.0, 5.0));
    positions.insert(4, (-5.0, 5.0));
    // Inner square hole [-2,2]² (ids 5-8).
    positions.insert(5, (-2.0, -2.0));
    positions.insert(6, (2.0, -2.0));
    positions.insert(7, (2.0, 2.0));
    positions.insert(8, (-2.0, 2.0));

    let outer = waffle_types::ClosedProfile {
        entity_ids: vec![1, 2, 3, 4],
        is_outer: true,
        vertex_ids: vec![1, 2, 3, 4],
        circle: None,
        spline_segments: vec![],
        arc_segments: vec![],
    };
    let hole = waffle_types::ClosedProfile {
        entity_ids: vec![5, 6, 7, 8],
        is_outer: false,
        vertex_ids: vec![5, 6, 7, 8],
        circle: None,
        spline_segments: vec![],
        arc_segments: vec![],
    };

    let depth = 3.0;
    let mut k = KernelV2Adapter::new();
    let faces = k
        .make_faces_from_profiles(
            &[outer, hole],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &positions,
        )
        .expect("holed sketch stages (KV14)");
    assert_eq!(faces.len(), 2, "output aligned 1:1 with input profiles");

    // The OUTER profile (index 0) carries the hole → annulus.
    let solid = k
        .extrude_face(faces[0], [0.0, 0.0, 1.0], depth)
        .expect("annulus extrudes");
    let mesh = k.tessellate(&solid, 0.001).expect("tessellate");
    let vol = mesh_signed_volume(&mesh);
    let expect = (10.0 * 10.0 - 4.0 * 4.0) * depth; // (outer − hole) × depth
    assert!(
        (vol.abs() - expect).abs() <= 1e-6 * expect,
        "annulus volume {vol} vs exact {expect}"
    );
}

/// KV12 Tier 1 end-to-end: an arc-segment profile extrudes to a clean prism
/// whose volume is the authored chord polygon's area × depth (the `arc_segments`
/// annotation is carried but the sampled polygon is what's swept).
#[test]
fn arc_segment_profile_extrudes_to_prism() {
    // Octagon — a stand-in for a chord-sampled rounded/arc profile — with an
    // arc_segments annotation spanning one corner.
    let n = 8usize;
    let radius = 2.0;
    let mut positions = HashMap::new();
    let mut vertex_ids = Vec::new();
    for i in 0..n {
        let a = std::f64::consts::TAU * (i as f64) / (n as f64);
        let id = (i + 1) as u32;
        positions.insert(id, (radius * a.cos(), radius * a.sin()));
        vertex_ids.push(id);
    }
    let profile = waffle_types::ClosedProfile {
        entity_ids: vertex_ids.clone(),
        is_outer: true,
        vertex_ids: vertex_ids.clone(),
        circle: None,
        spline_segments: vec![],
        arc_segments: vec![waffle_types::ArcSegment {
            start_vertex_index: 0,
            end_vertex_index: 2,
            center_u: 0.0,
            center_v: 0.0,
            radius,
        }],
    };
    let depth = 3.0;
    let mut k = KernelV2Adapter::new();
    let faces = k
        .make_faces_from_profiles(
            &[profile.clone()],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &positions,
        )
        .expect("arc-segment profile stages via its polygon (KV12 Tier 1)");
    let solid = k
        .extrude_face(faces[0], [0.0, 0.0, 1.0], depth)
        .expect("arc-segment prism extrudes");
    let mesh = k.tessellate(&solid, 0.001).expect("tessellate");
    let vol = mesh_signed_volume(&mesh);
    let expect = polygon_area(&profile.vertex_ids, &positions) * depth;
    assert!(
        (vol.abs() - expect).abs() <= 1e-6 * expect,
        "arc-segment prism volume {vol} vs exact {expect}"
    );
}

/// R0012-class regression: gear extrude on an OBLIQUE plane at world scale
/// ~70 (coordinates ~100). The planarity tripwire must be SCALE-RELATIVE:
/// f64 guarantees relative precision, so exactly-constructed mapped
/// vertices at this scale carry ~1e-13 of rounding — geometry, not error.
#[test]
fn gear_extrude_oblique_plane_at_scale() {
    let g = generate_gear_profile(&gear_params());
    let n: [f64; 3] = [
        -0.24020216902653416,
        -0.38111176393228574,
        -0.8927803433025224,
    ];
    let r = [0.0, 0.0, 1.0]; // engine ref-Z rule (|n_z| < 0.99)
    let cx = [
        r[1] * n[2] - r[2] * n[1],
        r[2] * n[0] - r[0] * n[2],
        r[0] * n[1] - r[1] * n[0],
    ];
    let l = (cx[0] * cx[0] + cx[1] * cx[1] + cx[2] * cx[2]).sqrt();
    let x = [cx[0] / l, cx[1] / l, cx[2] / l];
    let origin = [65.05307079902309, -42.5182833048961, -63.38652863797739];
    let mut k = KernelV2Adapter::new();
    let faces = k
        .make_faces_from_profiles(&[g.profiles[0].clone()], origin, n, x, &g.positions)
        .unwrap_or_else(|e| panic!("oblique gear staging: {e:?}"));
    let solid = k
        .extrude_face(faces[0], n, 48.75141123924903)
        .unwrap_or_else(|e| panic!("oblique gear extrude: {e:?}"));
    let mesh = k.tessellate(&solid, 0.001).expect("tessellate");
    let vol = mesh_signed_volume(&mesh);
    let area = polygon_area(&g.profiles[0].vertex_ids, &g.positions);
    let expect = area * 48.75141123924903;
    assert!(
        (vol.abs() - expect).abs() <= 1e-6 * expect,
        "oblique gear prism volume {vol} vs exact {expect}"
    );
}

/// Determinism: identical gear builds produce bit-identical meshes.
#[test]
fn gear_extrude_deterministic() {
    let build = || {
        let g = generate_gear_profile(&gear_params());
        let mut k = KernelV2Adapter::new();
        let f = k
            .make_faces_from_profiles(
                &[g.profiles[0].clone()],
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 1.0],
                [1.0, 0.0, 0.0],
                &g.positions,
            )
            .expect("profile");
        let s = k.extrude_face(f[0], [0.0, 0.0, 1.0], 5.0).expect("extrude");
        k.tessellate(&s, 0.001).expect("tessellate")
    };
    let (m1, m2) = (build(), build());
    assert_eq!(m1.vertices, m2.vertices);
    assert_eq!(m1.indices, m2.indices);
}
