//! PR-KV8 RED — gear (spline-annotated) profile extrusion + booleans.
//!
//! The assay corpus's single biggest blocker (73 of 193 cases) is the gear
//! profile: `make_faces_from_profiles` rejects any profile carrying
//! `spline_segments`. But a gear `ClosedProfile`'s **`vertex_ids` IS the
//! complete authored boundary polygon** — the involute flank sample points
//! plus the tip/root arc endpoints, generated by
//! `waffle_types::generate_gear_profile` (the same canonical polygon the
//! sketch solver and viewport use, and the polygon the legacy kernel
//! extruded). The `SplineSegment` entries are annotations over that
//! polygon (fitted control points for a NURBS-capable kernel); they do not
//! change the profile's authored geometry.
//!
//! So the principled kernel-v2 handling is to consume the authored polygon
//! exactly: the solid IS the extrusion of that (non-convex, exactly-simple)
//! polygon, with the exact ear-clip tessellation and exact shoelace area —
//! no new sampling, no approximation introduced by the kernel. This matches
//! the roadmap's designation of gear profiles as "non-convex CDT" work.
//!
//! Profiles with `arc_segments` stay WALLED: their vertex_ids carry arc
//! sample points where an EXACT cylindrical wall is representable
//! (post-KV5b), so polygonizing them would discard achievable exactness —
//! that support is its own milestone.

use std::collections::HashMap;

use kernel_v2::KernelV2Adapter;
use waffle_types::gear::{generate_gear_profile, GearParams};
use waffle_types::kernel::Kernel;

/// A small corpus-like gear: 11 teeth, module 3.47 (≈ R0012's first op).
fn gear_params() -> GearParams {
    GearParams {
        tooth_count: 11,
        module: 3.4745960218024408,
        pressure_angle_deg: 20.0,
        backlash: 0.0,
        center_x: 0.0,
        center_y: 0.0,
        rotation_offset: 0.0,
    }
}

/// Exact shoelace area of the profile's authored vertex_ids polygon.
fn polygon_area(vertex_ids: &[u32], positions: &HashMap<u32, (f64, f64)>) -> f64 {
    let pts: Vec<(f64, f64)> = vertex_ids.iter().map(|id| positions[id]).collect();
    let n = pts.len();
    let mut s2 = 0.0;
    for i in 0..n {
        let (x0, y0) = pts[i];
        let (x1, y1) = pts[(i + 1) % n];
        s2 += x0 * y1 - x1 * y0;
    }
    (s2 / 2.0).abs()
}

fn mesh_signed_volume(mesh: &waffle_types::kernel::RenderMesh) -> f64 {
    let p = |i: u32| {
        let k = (i as usize) * 3;
        [
            mesh.vertices[k] as f64,
            mesh.vertices[k + 1] as f64,
            mesh.vertices[k + 2] as f64,
        ]
    };
    let mut six_v = 0.0;
    for t in mesh.indices.chunks_exact(3) {
        let (a, b, c) = (p(t[0]), p(t[1]), p(t[2]));
        six_v += a[0] * (b[1] * c[2] - b[2] * c[1]) + a[1] * (b[2] * c[0] - b[0] * c[2])
            + a[2] * (b[0] * c[1] - b[1] * c[0]);
    }
    six_v / 6.0
}

#[test]
fn gear_profile_extrudes_with_exact_polygon_volume() {
    let g = generate_gear_profile(&gear_params());
    let profile = g.profiles[0].clone();
    assert!(
        !profile.spline_segments.is_empty(),
        "fixture must carry spline annotations"
    );
    let area = polygon_area(&profile.vertex_ids, &g.positions);
    assert!(area > 0.0);

    let mut k = KernelV2Adapter::new();
    let faces = k
        .make_faces_from_profiles(
            &[profile],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &g.positions,
        )
        .unwrap_or_else(|e| panic!("gear profile staging: {e:?}"));
    let depth = 5.0;
    let solid = k
        .extrude_face(faces[0], [0.0, 0.0, 1.0], depth)
        .unwrap_or_else(|e| panic!("gear extrude: {e:?}"));
    let mesh = k.tessellate(&solid, 0.001).expect("tessellate");
    let vol = mesh_signed_volume(&mesh);
    let expect = area * depth;
    // The polygon is the authored profile; its extrusion volume is exact
    // (ear-clip caps are an exact partition; walls are exact planes).
    assert!(
        (vol - expect).abs() <= 1e-9 * expect.max(1.0),
        "gear prism volume {vol} vs exact {expect}"
    );
}

/// Gear boss unioned onto a rectangular slab — the corpus's 2-op shape.
/// Volume by inclusion–exclusion: the gear prism's overlap with the slab is
/// gear_area × overlap height (footprint fully inside the slab).
#[test]
fn gear_boss_union_on_slab() {
    let g = generate_gear_profile(&gear_params());
    let profile = g.profiles[0].clone();
    let area = polygon_area(&profile.vertex_ids, &g.positions);
    // Addendum radius bounds the footprint.
    let r_out = g.addendum_radius;

    let mut k = KernelV2Adapter::new();
    // Slab: big rect covering the gear footprint, z ∈ [0, 4].
    let half = r_out * 2.0;
    let mut rect_positions = HashMap::new();
    rect_positions.insert(1, (-half, -half));
    rect_positions.insert(2, (half, -half));
    rect_positions.insert(3, (half, half));
    rect_positions.insert(4, (-half, half));
    let rect_profile = waffle_types::ClosedProfile {
        entity_ids: vec![1, 2, 3, 4],
        is_outer: true,
        vertex_ids: vec![1, 2, 3, 4],
        circle: None,
        spline_segments: vec![],
        arc_segments: vec![],
    };
    let rf = k
        .make_faces_from_profiles(
            &[rect_profile],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &rect_positions,
        )
        .expect("rect profile");
    let slab = k.extrude_face(rf[0], [0.0, 0.0, 1.0], 4.0).expect("slab");

    // Gear boss: z ∈ [2, 9] (sketch plane mid-slab → boss pokes out the top;
    // avoids any coplanar contact with the slab caps).
    let gf = k
        .make_faces_from_profiles(
            &[profile],
            [0.0, 0.0, 2.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &g.positions,
        )
        .expect("gear profile");
    let boss = k
        .extrude_face(gf[0], [0.0, 0.0, 1.0], 7.0)
        .expect("gear boss");

    let out = k
        .boolean_union(&slab, &boss)
        .unwrap_or_else(|e| panic!("gear boss union: {e:?}"));
    let mesh = k.tessellate(&out, 0.001).expect("tessellate union");
    let vol = mesh_signed_volume(&mesh);
    let slab_v = (2.0 * half) * (2.0 * half) * 4.0;
    let overlap = area * 2.0; // gear prism inside slab: z ∈ [2, 4]
    let expect = slab_v + area * 7.0 - overlap;
    assert!(
        (vol - expect).abs() <= 1e-9 * expect,
        "union volume {vol} vs exact {expect}"
    );
}

/// Gear pocket cut into a slab (the cut direction of the same class).
#[test]
fn gear_pocket_cut_into_slab() {
    let g = generate_gear_profile(&gear_params());
    let profile = g.profiles[0].clone();
    let area = polygon_area(&profile.vertex_ids, &g.positions);
    let r_out = g.addendum_radius;

    let mut k = KernelV2Adapter::new();
    let half = r_out * 2.0;
    let mut rect_positions = HashMap::new();
    rect_positions.insert(1, (-half, -half));
    rect_positions.insert(2, (half, -half));
    rect_positions.insert(3, (half, half));
    rect_positions.insert(4, (-half, half));
    let rect_profile = waffle_types::ClosedProfile {
        entity_ids: vec![1, 2, 3, 4],
        is_outer: true,
        vertex_ids: vec![1, 2, 3, 4],
        circle: None,
        spline_segments: vec![],
        arc_segments: vec![],
    };
    let rf = k
        .make_faces_from_profiles(
            &[rect_profile],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &rect_positions,
        )
        .expect("rect profile");
    let slab = k.extrude_face(rf[0], [0.0, 0.0, 1.0], 4.0).expect("slab");

    // Gear tool: enters through the top face (z ∈ [3, 6]) → pocket depth 1.
    let gf = k
        .make_faces_from_profiles(
            &[profile],
            [0.0, 0.0, 3.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &g.positions,
        )
        .expect("gear profile");
    let tool = k
        .extrude_face(gf[0], [0.0, 0.0, 1.0], 3.0)
        .expect("gear tool");
    let out = k
        .boolean_subtract(&slab, &tool)
        .unwrap_or_else(|e| panic!("gear pocket cut: {e:?}"));
    let mesh = k.tessellate(&out, 0.001).expect("tessellate cut");
    let vol = mesh_signed_volume(&mesh);
    let expect = (2.0 * half) * (2.0 * half) * 4.0 - area * 1.0;
    assert!(
        (vol - expect).abs() <= 1e-9 * expect,
        "pocket volume {vol} vs exact {expect}"
    );
}

/// Arc-segment profiles stay WALLED (their vertex_ids carry arc samples
/// where exact cylindrical walls are representable — polygonizing them
/// would discard achievable exactness).
#[test]
fn arc_segment_profile_stays_typed_wall() {
    let mut positions = HashMap::new();
    positions.insert(1, (0.0, 0.0));
    positions.insert(2, (1.0, 0.0));
    positions.insert(3, (1.0, 1.0));
    positions.insert(4, (0.0, 1.0));
    let profile = waffle_types::ClosedProfile {
        entity_ids: vec![1, 2, 3, 4],
        is_outer: true,
        vertex_ids: vec![1, 2, 3, 4],
        circle: None,
        spline_segments: vec![],
        arc_segments: vec![waffle_types::ArcSegment {
            start_vertex_index: 0,
            end_vertex_index: 1,
            center_u: 0.5,
            center_v: -0.5,
            radius: 0.7,
        }],
    };
    let mut k = KernelV2Adapter::new();
    let err = k
        .make_faces_from_profiles(
            &[profile],
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            &positions,
        )
        .expect_err("arc-segment profile stays walled");
    assert!(
        format!("{err}").contains("not supported"),
        "typed NotSupported, got {err}"
    );
}

/// Determinism: identical gear builds produce bit-identical meshes.
#[test]
fn gear_extrude_deterministic() {
    let build = || {
        let g = generate_gear_profile(&gear_params());
        let mut k = KernelV2Adapter::new();
        let f = k
            .make_faces_from_profiles(
                &[g.profiles[0].clone()],
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 1.0],
                [1.0, 0.0, 0.0],
                &g.positions,
            )
            .expect("profile");
        let s = k.extrude_face(f[0], [0.0, 0.0, 1.0], 5.0).expect("extrude");
        k.tessellate(&s, 0.001).expect("tessellate")
    };
    let (m1, m2) = (build(), build());
    assert_eq!(m1.vertices, m2.vertices);
    assert_eq!(m1.indices, m2.indices);
}
