/**
 * STEP import tests (task #138, SI1 — docs/step_import_roadmap.md).
 *
 * Imports a small STEP cube (fixtures/cube.step, 10mm, generated by truck's
 * own writer — license-clean) through the same ImportStep message the file
 * picker sends, then verifies the imported body is FIRST-CLASS:
 * renders as a body, lists in the bodies panel, its planar faces resolve a
 * sketch plane via computeFacePlane (the sketch-on-face data path), and the
 * placement dialog re-positions it through EditFeature.
 *
 * importStepFromText is the test-setup entry (a real <input type=file>
 * picker cannot be driven from Playwright); the toolbar button is verified
 * to exist separately.
 */
import fs from 'fs';
import { test, expect } from './helpers/waffle-test.js';
import {
	collectCrashErrors,
	expectNoAnyCrash,
	getFeatureTree,
	getMeshes,
	waitForFeatureCount,
} from './helpers/state.js';

const CUBE_STEP = fs.readFileSync(
	new URL('./fixtures/cube.step', import.meta.url),
	'utf8'
);

/**
 * Import the cube fixture and wait for the feature to land. The import
 * opens the placement modal with a ghost preview; pass `confirm: true`
 * to Apply it away (most tests want a placed body).
 */
async function importCube(page, { confirm = true } = {}) {
	const ok = await page.evaluate(
		(text) => window.__waffle.importStepFromText('cube.step', text),
		CUBE_STEP
	);
	expect(ok).toBe(true);
	await waitForFeatureCount(page, 1, 10000);
	const dialog = page.locator('[data-testid="import-step-dialog"]');
	await dialog.waitFor({ state: 'visible', timeout: 5000 });
	if (confirm) {
		await page.locator('[data-testid="import-apply"]').click();
		await dialog.waitFor({ state: 'hidden', timeout: 10000 });
	}
}

/** Axis-aligned bounding box over all rendered meshes ([min,max] triples). */
async function meshBBox(page) {
	return page.evaluate(() => window.__waffle.getMeshBoundingBox());
}

test.describe('STEP import', () => {
	test('import lands an ImportedBody feature that renders as a body', async ({ waffle }) => {
		const crashes = collectCrashErrors(waffle.page);
		await importCube(waffle.page);

		const tree = await getFeatureTree(waffle.page);
		expect(tree.features).toHaveLength(1);
		expect(tree.features[0].operation.type).toBe('ImportedBody');
		expect(tree.features[0].name).toBe('Import cube.step');
		// Payload is embedded compressed, not raw text.
		expect(tree.features[0].operation.params.blob_encoding).toBe('deflate-base64');
		expect(tree.features[0].operation.params.blob.length).toBeLessThan(CUBE_STEP.length);

		// It renders: one mesh with the cube's 6 pick ranges, 10mm extent.
		const meshes = await getMeshes(waffle.page);
		expect(meshes).toHaveLength(1);
		expect(meshes[0].faceRangeCount).toBe(6);
		const { min, max } = await meshBBox(waffle.page);
		for (let k = 0; k < 3; k++) {
			expect(max[k] - min[k]).toBeCloseTo(0.01, 4); // 10mm in meters
		}

		// It lists as a body.
		await expect(waffle.page.locator('.body-item')).toHaveCount(1);

		expectNoAnyCrash(crashes);
	});

	test('imported planar faces resolve a sketch plane (sketch-on-face data path)', async ({ waffle }) => {
		const crashes = collectCrashErrors(waffle.page);
		await importCube(waffle.page);

		const plane = await waffle.page.evaluate(() => {
			const mesh = window.__waffle.getMeshes()[0];
			const withRef = (mesh.faceRanges ?? []).filter(r => r.geom_ref);
			if (withRef.length === 0) return { error: 'no geom_refs on imported faces' };
			// Every cube face is planar; take the first that resolves.
			for (const range of withRef) {
				const p = window.__waffle.computeFacePlane(range.geom_ref);
				if (p) return { origin: p.origin, normal: p.normal, count: withRef.length };
			}
			return { error: 'no face resolved a plane', count: withRef.length };
		});
		expect(plane.error, plane.error).toBeUndefined();
		expect(plane.count).toBe(6);
		// Unit normal.
		const n = plane.normal;
		const len = Math.hypot(n[0], n[1], n[2]);
		expect(len).toBeCloseTo(1.0, 6);

		expectNoAnyCrash(crashes);
	});

	test('import opens the placement modal with a ghost preview; cancel discards the import', async ({ waffle }) => {
		const crashes = collectCrashErrors(waffle.page);
		await importCube(waffle.page, { confirm: false });

		// Modal is open on the fresh feature and the body renders as a ghost.
		const ghost = await waffle.page.evaluate(() => ({
			ghostId: window.__waffle.getGhostFeatureId(),
			featureId: window.__waffle.getFeatureTree().features[0].id,
		}));
		expect(ghost.ghostId).toBe(ghost.featureId);
		await expect(
			waffle.page.locator('[data-testid="import-ghost-hint"]')
		).toBeVisible();

		// Live preview: typing an offset moves the (ghost) body WITHOUT Apply.
		await waffle.page.locator('[data-testid="import-tx"]').fill('30');
		await waffle.page.waitForFunction(() => {
			const f = window.__waffle.getFeatureTree()?.features?.[0];
			return Math.abs((f?.operation?.params?.translation_m?.[0] ?? 0) - 0.03) < 1e-9;
		}, { timeout: 10000 });

		// Cancel: the fresh import is discarded entirely — even after a live
		// preview edit.
		await waffle.page.locator('[data-testid="import-cancel"]').click();
		await expect(
			waffle.page.locator('[data-testid="import-step-dialog"]')
		).toBeHidden({ timeout: 10000 });
		await waffle.page.waitForFunction(
			() => window.__waffle.getFeatureTree()?.features?.length === 0,
			{ timeout: 10000 }
		);
		const ghostAfter = await waffle.page.evaluate(() => window.__waffle.getGhostFeatureId());
		expect(ghostAfter).toBeNull();

		expectNoAnyCrash(crashes);
	});

	test('placement dialog repositions the imported body via EditFeature', async ({ waffle }) => {
		const crashes = collectCrashErrors(waffle.page);
		await importCube(waffle.page);
		const before = await meshBBox(waffle.page);

		// Re-open the placement dialog for the feature and move +20mm in X.
		await waffle.page.evaluate(() => {
			const tree = window.__waffle.getFeatureTree();
			window.__waffle.showImportDialogForEdit(tree.features[0].id);
		});
		const dialog = waffle.page.locator('[data-testid="import-step-dialog"]');
		await expect(dialog).toBeVisible();
		await waffle.page.locator('[data-testid="import-tx"]').fill('20');
		await waffle.page.locator('[data-testid="import-rz"]').fill('45');
		await waffle.page.locator('[data-testid="import-apply"]').click();
		await expect(dialog).toBeHidden({ timeout: 10000 });

		// The feature's params updated (mm → meters) and the mesh moved.
		await waffle.page.waitForFunction(() => {
			const f = window.__waffle.getFeatureTree()?.features?.[0];
			return Math.abs((f?.operation?.params?.translation_m?.[0] ?? 0) - 0.02) < 1e-9;
		}, { timeout: 10000 });
		const tree = await getFeatureTree(waffle.page);
		expect(tree.features[0].operation.params.rotation_deg[2]).toBeCloseTo(45, 9);

		const after = await meshBBox(waffle.page);
		expect(after.min[0]).toBeGreaterThan(before.min[0] + 0.01);

		expectNoAnyCrash(crashes);
	});

	test('toolbar has an Import tool outside sketch mode', async ({ waffle }) => {
		await expect(
			waffle.page.locator('button', { hasText: 'Import' }).first()
		).toBeVisible();
	});
});
