//! predicate-gen — code generator for cherchi-rs's clean-room indirect
//! predicates (kernel-rewrite milestone M7).
//!
//! Dev tooling, OUTSIDE the kernel crate layering: nothing ships this
//! crate; it emits checked-in Rust source. No dependencies.
//!
//! Pipeline:
//!
//! 1. [`ir`] — a small SSA expression IR (variables, `+`, `−`, `×`; no
//!    division — denominator signs are handled by Attene's parity rule).
//! 2. [`fpg`] — Meyer-Pion 2008 forward error analysis: propagate
//!    `(bound, error)` through the expression assuming `|v| ≤ 1`,
//!    rounding every constant conservatively UP; the final error is the
//!    semi-static filter constant `δ(1)` of Attene 2025 Appendix A.
//! 3. [`codegen`] — straight-line Rust emission (filtered f64 + exact
//!    `dashu::rational::RBig` over the same polynomial).
//! 4. [`orient3d`] — the concrete LPI/TPI lambdas and the 14 canonical
//!    `orient3d` instances; [`orient3d::generate_file`] assembles
//!    `crates/cherchi-rs/src/predicates/indirect/generated.rs`.
//!
//! Clean-room sources (papers only — the LGPL C++ implementation was
//! not consulted):
//!
//! - `refs/text/attene-predicates.txt` (Attene 2025)
//! - `refs/text/mesh_arrangement.txt` §4.2.2 (Cherchi 2020)
//! - `refs/text/meyer_pion2008_fpg.txt` (Meyer & Pion 2008)

pub mod codegen;
pub mod fpg;
pub mod ir;
pub mod lessthan;
pub mod orient2d;
pub mod orient3d;

/// Path of the emitted file, relative to this crate's manifest dir.
pub const OUTPUT_RELATIVE: &str = "../cherchi-rs/src/predicates/indirect/generated.rs";

/// Generate the complete `generated.rs` module for cherchi-rs:
/// the LPI/TPI lambda evaluators plus three predicate families —
/// `orient3d` (M7a), `orient2d_{xy,yz,zx}` and `less_than_on_{x,y,z}`
/// (M7b) — each with filtered/interval/exact tiers and canonical
/// dispatchers.
pub fn generate_file() -> String {
    let lpi = orient3d::lpi_lambda_spec();
    let tpi = orient3d::tpi_lambda_spec();

    let mut out = String::new();
    out.push_str(
        "//! GENERATED by predicate-gen — do not hand-edit; regenerate with\n\
         //! `cargo run -p predicate-gen`.\n\
         //!\n\
         //! Indirect predicate catalog over explicit / LPI / TPI points:\n\
         //! lambda evaluators (filtered f64 + interval `Iv` + exact `RBig`),\n\
         //! the 14 canonical `orient3d` instances of Attene 2025 §6 (EEEE\n\
         //! delegates to the pure adaptive CR6 predicate), the 27 canonical\n\
         //! `orient2d_{xy,yz,zx}` instances of Cherchi 2020 Appendix A (EEE\n\
         //! delegates to the CR10 predicate), the 15 canonical\n\
         //! `less_than_on_{x,y,z}` instances of Cherchi 2020 Appendix B (EE\n\
         //! is a direct f64 comparison), and the canonical tier dispatchers.\n\
         //!\n\
         //! CLEAN-ROOM: derived only from Attene 2025, Cherchi 2020 §4.2.2 +\n\
         //! Appendices A/B and Meyer-Pion 2008 (FPG) — see the\n\
         //! `crates/predicate-gen` sources for the formulations and paper\n\
         //! line citations.\n\n\
         // Machine-generated straight-line code: suppress style lints wholesale\n\
         // (single-use bindings, long functions, etc. are inherent to SSA\n\
         // emission and harmless). rustfmt is kept away via the\n\
         // `#[rustfmt::skip]` on the `mod generated;` declaration so the\n\
         // checked-in bytes stay identical to the generator output (the\n\
         // freshness test diffs them byte-for-byte).\n\
         #![allow(clippy::all)]\n\n\
         use super::{support, GenericPoint3D, Iv, LambdaExact, LambdaF64, LambdaIv, Sign};\n\
         use cad_primitives::{Point2, Point3};\n\n",
    );
    out.push_str(&orient3d::section(&lpi, &tpi));
    out.push_str(&orient2d::section(&lpi, &tpi));
    out.push_str(&lessthan::section(&lpi, &tpi));
    out
}
